#sqlite: &sqlite
  #adapter: sqlite3
  #database: db/<%= ENV['RAILS_ENV'] %>.sqlite3

#mysql: &mysql
  #adapter: mysql2
  #username: root
  #password:
  #database: invoicer_<%= ENV['RAILS_ENV'] %>

postgresql: &postgresql
  adapter: postgresql
  username: postgres
  password:
  database: invoicer_<%= ENV['RAILS_ENV'] %>
  min_messages: ERROR

defaults: &defaults
  pool: 5
  timeout: 5000
  host: localhost
  <<: *<%= ENV['DB'] || "sqlite" %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
